//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string year { get; set; }
        public string regno { get; set; }
        public string NATIONAL_NO { get; set; }
        public string Fname { get; set; }
        public string NAME { get; set; }
        public string Father_Name { get; set; }
        public string Birth_Date { get; set; }
        public string ID_No { get; set; }
        public string Sex_Code { get; set; }
        public string COMPANY_CODE { get; set; }
        public string mg_code { get; set; }
        public string Organ_Code { get; set; }
        public string Dept_Code { get; set; }
        public string PYRLCMP_CODE { get; set; }
        public string Service_Year { get; set; }
        public string EMPLOYM_TYPE { get; set; }
        public string EDUCAT_LEVEL { get; set; }
        public string Post_Grade { get; set; }
        public string Job_Grade { get; set; }
        public string Post_Title { get; set; }
        public string System_Code { get; set; }
        public string C6626 { get; set; }
        public string C6352 { get; set; }
        public string C5184 { get; set; }
        public string C6373 { get; set; }
        public string C6356 { get; set; }
        public string C5185 { get; set; }
        public string C6357 { get; set; }
        public string C6358 { get; set; }
        public string C6369 { get; set; }
        public string C6359 { get; set; }
        public string C6362 { get; set; }
        public string C6363 { get; set; }
        public string C5181 { get; set; }
        public string C6299 { get; set; }
        public string C6178 { get; set; }
        public string C6177 { get; set; }
        public string C6364 { get; set; }
        public string C6365 { get; set; }
        public string C6353 { get; set; }
        public string C5192 { get; set; }
        public string C6366 { get; set; }
        public string C6262 { get; set; }
        public string C6367 { get; set; }
        public string C6207 { get; set; }
        public string C6206 { get; set; }
        public string C6372 { get; set; }
        public string C6368 { get; set; }
        public string C5207 { get; set; }
        public Nullable<long> Main_NetSalary { get; set; }
        public Nullable<long> KI_NetSalary { get; set; }
    }
}
